### ISSUE TITLE
How to interact with Smart Contracts.

### ISSUE THREAD

**Issue by dAppDev03** [RootSoft/walletconnect-dart-sdk#45] opened 2022-05-19 17:17 UTC
This is an amazing plugin which will let the mobile dApps connect to the Decentralised Wallets ( MetaMask , Trust Wallet). **_Thanks_** for such an amazing plugin.

 Can we add a feature to interact with smart contracts straight from the mobile dApp ?

**Comment by bogdynator** [comment] 2022-05-26 07:39
Some news here? I am interested in that feature too

**Comment by RootSoft** [comment] 2022-05-27 08:37
I will publish a tutorial guide soon on how I've build https://play.google.com/store/apps/details?id=art.sooq.app&hl=ar&gl=US and https://sooq.art

This uses smart contracts on the Algorand blockchain.

**Comment by bogdynator** [comment] 2022-05-28 17:12
can you please provide an example of sendTransaction using data param? Because I am trying to use that function to interact with a smart contract, but the function that is always called is receive function

**Comment by bogdynator** [comment] 2022-05-28 18:20
Also, I see that EthereumWalletConnectProvider return the address of the transaction as string. Is there a method to know if the transaction was completed or is it still in pending/failed?

**Comment by bobwith2bees** [comment] 2022-05-29 21:49
@bogdynator 

You can peek at this example that shows a sendCustomRequest() that has parameters in the call.  It's still a eth_signTypedData request for the wallet to approve.  Not sending a transaction to a smart contract.
- https://gitlab.com/graflr/flutter_rarible_example/-/blob/main/lib/main.dart#L431

Are you trying to talk to an arbitrary contract ABI?  And you want to use WalletConnect to handle the credentials with your wallet (and fund the GAS fees etc.)?     That's outside of my skills, but wanted to try and help.

**Comment by bogdynator** [comment] 2022-06-01 15:58
Thank you for your example, I was trying to talk with a deployed contract. I found a way, I am using web3dart now for interaction, and that library give you the opportunity to generate a class with build_runner from the contract abi. It's easier. I still use the wallet connect to comunicate with Metamask and get the address from which I am sending the tx.

**Comment by zzyakenzz** [comment] 2022-06-02 17:07
Hi @bogdynator Do you know how to add custom RPC to walletconnect?  And I got error when make transaction: ERR JSON-RPC error -32000: Internal JSON-RPC error.

**Comment by banjuanshua** [comment] 2022-06-03 08:25
Hi @bogdynator Can you give out a example to let me kown how to do this

**Comment by zzyakenzz** [comment] 2022-06-18 13:02
I got error: Internal JSON-RPC error because I provide wrong nonce number. nonce number as index of the list. Issue 2: The custom RPC config in WalletConnect, do not need implement by code

**Comment by RootSoft** [comment] 2022-06-28 14:07
@zzyakenzz please create a new issue with a reproducable example and how I can generate the error.
Haven't seen this error before. Closing this issue.

**Closed by RootSoft** 2022-06-28 14:07 UTC
